In [2]:
import pymysql
import pandas as pd
import warnings 
warnings.filterwarnings('ignore')
try:
     conn = pymysql.connect(
     host="localhost",
     user="root",
     password="",
     database="movies"
)

except Exception as e:
     print("Error: an error occurred.")

In [3]:
pd.read_sql("SELECT * FROM Flipshope_data", conn)

,Campaign_Name,Id,Status,Date,Amount,Payout,Sub_Id
0,GoDaddy,22517815,pending,2024-11-29,33.56,173.76,store_page
1,GoDaddy,22299218,pending,2024-11-29,11.96,61.87,atrf
2,Ajio,22433679,pending,2024-11-30,599.00,68.29,store_page
3,Ajio,22433678,pending,2024-11-30,975.00,111.15,store_page
4,Ajio,22431778,pending,2024-11-30,947.00,134.95,store_page
...,...,...,...,...,...,...,...
3288,Flipkart [CPS] IN,1094244725,pending,2024-11-01,5999.00,153.57,app
3289,Flipkart [CPS] IN,1094244386,pending,2024-11-01,365.00,9.34,web
3290,Flipkart [CPS] IN,1094239300,pending,2024-11-01,149.00,2.54,telegram
3291,Flipkart [CPS] IN,1094231078,pending,2024-11-01,149.00,2.54,app
3292,Flipkart [CPS] IN,1094228197,pending,2024-11-01,149.00,2.54,telegram